Replaces the schema validator tv4 with ajv
interledger-deprecated/five-bells-shared pull request #169
Opened 2016-11-30 17:07 UTC by dappelt

The current schema validator tv4 is replaced with ajv. The new validator is faster and checks the schema soundness more thoroughly.

In addition, this PR fixes two broken schemas. The field "required" was within the array "properties". Therefore, the schema validator did not check that the field specified by required does exist.

2016-11-30 17:32 UTC, sentientwaffle requested changes
`tv4` is still referenced in `services/validate.js`

2016-12-01 15:37 UTC, sentientwaffle requested changes
Please link this against five-bells-ledger and run the ledger's unit tests -- even with the `require()` fix there are plenty of errors (to do with a changed uri schema, it would seem).

2016-12-01 15:37 UTC, sentientwaffle commented on services/validate.js
> +      validator.addSchema(JSON.parse(path.join(baseDir, fileName)), fileName)
This should be `validator.addSchema(require(path.join(baseDir, fileName)), fileName)`; JSON-parsing the path doesn't make sense.

2016-12-01 19:21 UTC, dappelt commented on services/validate.js
> +      validator.addSchema(JSON.parse(path.join(baseDir, fileName)), fileName)
Thanks for the heads-up. I fixed the code. However, the unit tests are still failing. The validation results of `ajv` seem to be fine, but the results of `tv4` do not make sense to me.

Take for example the unit test `PUT /transfers/:id should return 422 if the source amount is zero` in `putTransferSpec.js`. In this unit test, the function [`this.tv4.validateMultiple(data, schema + '.json')`](https://github.com/interledgerjs/five-bells-shared/blob/master/lib/validator.js#L81)  is called with schema=`Transfer` and data:
```
{
    id: '155dff3f-4915-44df-a707-acc4b527bcbd',
    ledger: 'http://localhost',
    debits: [{
        account: 'http://localhost/accounts/alice',
        amount: '0',
        authorized: true
    }],
    credits: [{
        account: 'http://localhost/accounts/bob',
        amount: '10'
    }],
    state: 'executed'
}
```
And the result returned by `tv4` is: `{ errors: [], missing: [], valid: true, schema: 'Transfer' }`, which indicates that `data` complies to `Transfer.json`.

According to [TransferTemplate.json](https://github.com/interledgerjs/five-bells-shared/blob/master/schemas/TransferTemplate.json), the property `id` should be an URI, but `tv4` does not seem to validate this field properly. Even when I remove the property `id` or assign obscure values it gives me the same result as above, e.g. the validation succeeds for `data`:
```
{
    ledger: 'http://localhost',
    debits: [{
        account: 'http://localhost/accounts/alice',
        amount: '0',
        authorized: true
    }],
    credits: [{
        account: 'http://localhost/accounts/bob',
        amount: '10'
    }],
    state: 'executed'
}
```
Surprisingly, if the property `ledger` is not an URI, the validation fails. So `tv4` knows how an URI should look like ...

In contrast, `ajv` produces the expected validation result and, hence, the unit tests are failing.

Am I missing something? Is `tv4` simply not working correctly or is there an explanation for this?

2016-12-01 21:29 UTC, sentientwaffle commented on services/validate.js
> +      validator.addSchema(JSON.parse(path.join(baseDir, fileName)), fileName)
You're right, tv4 was being too lenient with the format and allowing non-URIs to pass. That's fixed in https://github.com/interledgerjs/five-bells-ledger/pull/379. The tests still don't pass, though.

2016-12-02 16:27 UTC, dappelt commented on services/validate.js
> +      validator.addSchema(JSON.parse(path.join(baseDir, fileName)), fileName)
In combination with your [PR](https://github.com/interledgerjs/five-bells-ledger/pull/379) the ledger's tests are passing.

I ran as well the connector's unit tests against the new validator code. I fixed some failing test cases, but [one test case still has to be fixed](https://github.com/interledgerjs/ilp-connector/issues/262). Thanks for your input.

2016-12-02 18:24 UTC, sentientwaffle commented on services/validate.js
> +      validator.addSchema(JSON.parse(path.join(baseDir, fileName)), fileName)
I've opened a PR for the [quote issue](https://github.com/interledgerjs/ilp-connector/pull/263), and other for an issue in the [notary](https://github.com/interledgerjs/five-bells-notary/pull/84).

I also ran into another bug:

```diff --git a/lib/validator.js b/lib/validator.js
index 426efc4..358a9f7 100644
--- a/lib/validator.js
+++ b/lib/validator.js
@@ -97,7 +97,7 @@ class Validator {
    * @returns {void}
    */
   validateUriParameter (paramId, paramValue, schema) {
-    const isValid = this.ajv.validate(paramValue, schema + '.json')
+    const isValid = this.ajv.validate(schema + '.json', paramValue)
     if (!isValid) {
       throw new InvalidUriParameterError(paramId + ' is not a valid ' + schema,
         this.ajv.errors)
@@ -120,7 +120,7 @@ class Validator {
     const json = yield parse(ctx)

     if (schema) {
-      const isValid = this.ajv.validate(json, schema + '.json')
+      const isValid = this.ajv.validate(schema + '.json', json)
       if (!isValid) {
         throw new InvalidBodyError('JSON request body is not a valid ' + schema,
           this.ajv.errors)
```

2016-12-05 14:07 UTC, dappelt commented on services/validate.js
> +      validator.addSchema(JSON.parse(path.join(baseDir, fileName)), fileName)
Fixed.

The ledger's unit and integration tests run smoothly when npm linking this PR. When using the branch [ilp-connector/tree/da-fix-tests-for-ajv](https://github.com/interledgerjs/ilp-connector/tree/da-fix-tests-for-ajv), the connector's tests are also working against this PR.

2016-12-05 16:38 UTC, sentientwaffle approved these changes

2016-12-05 17:11 UTC, merged